### ISSUE TITLE
CKEditor with redux-form

### ISSUE THREAD

**Issue by drkgrntt** [codeslayer1/react-ckeditor#18]
I'm trying to use CKEditor with redux-form, but I'm not exactly sure how to use it within a <Field /> component correctly. I've tried this:

```
<Field
  label="Content"
  name="content"
  component={CKEditor}
/>
```

But when I do a simple test with:

```
onSubmit(values) {
  console.log(values);
}
```
I'm not getting anything back. I assume I'll need to use the content prop to get it to include the editor content into the values argument, but I'm not sure how I might do that. 

Thanks in advance for your help.

**Comment by codeslayer1** [comment]
Sorry for the late reply. Was out of town.

You can use CKEditor with Field like this. First change your Field to this:

```
<Field
  name="content"
  label ="Content"
  component={props =>
    <CKEditor
      content={props.value}
      events={{
        "change": param => onChange(param)
      }} />
    }
/>
```

Make sure you pass onChange function to your redux form. Then you can access the ckeditor data like this in onChange function.

```
onChange(evt){
    console.log("onChange fired with data ", evt.editor.getData());
}
```

Then you can simply save this data in your redux store whenever it changes and access it directly from store while submitting. I am not sure if there is a way for redux-form to directly bind your custom data to store since I haven't used it my projects. But I just now tried the above code in a sample project and it was working fine. 

You can read more about using custom components with redux-form here - https://redux-form.com/6.0.0-alpha.4/docs/faq/customcomponent.md/

Let me know in case you still face any issues.

**Comment by drkgrntt** [comment]
Thanks for your help with this! Unfortunately, I'm still having problems.

I currently have my field laid out as this:

          <Field
            label="Story Content"
            name="content"
            component={(props) =>
              <CKEditor
                content={props.value}
                events={{
                  "change": (param) => this.onChange(param)
                }}
              />
            }
          />

along with my onChange function:

```
  onChange(event) {
    console.log(event.editor.getData());
  }
```

While console.log() prints it out, I'm having trouble saving the data to my redux store. When I tried making the "change" event `"change": (param) => props.onChange(param)` as laid out in the redux-form FAQ page you referenced, I got an error that said props.onChange is not a function. 

I guess my question is how do I save the data to the store when I change it and then access it when I submit the form?

Thanks again for your help. Much appreciated.

**Comment by avinmathew** [comment]
I got it working with Redux Forms like this:

```js
const renderEditor = ({ input }) => {
  return (
      <CKEditor
        content={input.value}
        events={{
          change: event => input.onChange(event.editor.getData())
        }}
      />
   );
};
```
```js
<Field
  name="myField"
  component={renderEditor}
/>
```

**Comment by drkgrntt** [comment]
It works! Thanks much!

**Comment by scilganon** [comment]
it does not work in IE11 :(

**Comment by Nastya-Piu** [comment]
I fixed it with ckeditor5-react by
```javascript
renderEditor({input}) {
    return (
      <CKEditor
        data={input.value}
        editor={ ClassicEditor }
        onChange={(event, editor) => {
            return input.onChange(editor.getData())
          }
        }
      />
    )
  }
```
```javascript
<Field name="text" component={this.renderEditor} />
```

**Comment by desienjelina** [comment]
fddf### dfdf**dfd**

**Comment by desienjelina** [comment]
test``

**Comment by desienjelina** [comment]
testtttttttt
