### ISSUE TITLE
CKEdtior renders with empty content although it exists in the props

### ISSUE THREAD

**Issue by rosyaniv** [codeslayer1/react-ckeditor#23]
I have a React\Flux app. When entering the parent component of the CKEditor, I'm fetching data from the server, so in the initial loading, the 'content' prop of the CKEditor is empty, and after a few moments (when the fetching is done) the CKEditor component receives the content (props.content), but it doesn't always show it.
It actually depends on the loading of the parent component, when the user refreshes the page then everything works good, but if the user navigates from another component (different route) then the props.content in the CKEditor contains the content, but nothing is being shown in the CKEditor text box.
(Just to make it clear - in both cases the props.content of the CKEditor (eventually) contains the real content, but only in one case it shows it (meaning, working properly)).
Could you please assist?
Thanks,

**Comment by codeslayer1** [comment]
Hi, This must be happening because your CKEditor instance was rendered before there was data in the content prop. To fix this, you must only render your CKEditor instance after your data is fetched. So you can add a check in your code like this - 

```
if(props.content == null){
    return null;
}else{
    return <Ckeditor ...>
}
```
The above check will render CKeditor once the props.content is populated with your data.

In case you need to forcefully update the content of already rendered CKEditor after the data is retrieved from server then refer this issue - #13 . Here I have explained how to update content in CKEditor.

**Comment by rosyaniv** [comment]
#13 it solved it. Thanks!

**Comment by dlewis-esri** [comment]
I have a better fix for this that allows the editor to be constructed and receive updates
`class Wysiwyg extends React.Component {
	constructor() {
		super();
		this.editor = null;
	}
	componentDidUpdate() {
		if (this.editor) {
			this.editor.setData(this.props.value);
		}
	}
	render() {
		const editorValue = this.props.value || '';
		return (
			<div className='wysiwyg-wrapper'>
				<CKEditor
					content={editorValue}
					events={{
						"change": (evt) => {
							const newContent = evt.editor.getData();
							this.props.onChange(newContent);
						},
						"loaded": (evt) => {
							this.editor = evt.editor;
						}
					}}
				/>
			</div>
		);
	}
}`
