### ISSUE TITLE
ckeditor takes a delay of 3 to 4 sec to load into a modal popup

### ISSUE THREAD

**Issue by damild15** [codeslayer1/react-ckeditor#35]
hi , i need some help please . when  I click on the modal popup to be open, the ckeditor takes a delay of like 3-4 sec to be loaded, can you tell me how to resolve this please ?

**Comment by codeslayer1** [comment]
That happens because it takes some time for CKEditor scripts to be loaded from the network. The scripts start loading once CKEditor component renders when your popup opens. 

The solution to prevent this delay is to preload the CKEditor script before opening your modal (by using load-script or some other library).

**Comment by damild15** [comment]
a ok can you provide me a example please?
this is mine:
import React from 'react';
import CKEditor from "react-ckeditor-component";


 <CKEditor
                  activeClass="p10"
                  content={this.state.ckcontent}
                  events={{
                    // "blur": this.onBlur,
                    // "afterPaste": this.afterPaste,
                  "change":(ev) => this.onChange(ev),
                  "instanceReady":(ev) => this.onInstanceReady(ev),
                  "isScriptLoaded":true

                  }}
                 />

**Comment by codeslayer1** [comment]
You can read the docs for load-script [here](https://github.com/eldargab/load-script). Since this is not an issue with the package, I am closing this issue,
