### ISSUE TITLE
Plugins loading docs needed

### ISSUE THREAD

**Issue by ghost** [codeslayer1/react-ckeditor#53]
Hi. At first, thanks for this awesome component.
I know that issues is not a right place for asking questions, but how can I load a plugins? Is it even possible?
I am trying to pass a path for plugin js-file directly into "scriptUrl" props,

`scriptUrl={'./cke-plugins/justify/plugin.js'}`

but this leads to an error.

`CKEditor not found`

**Comment by codeslayer1** [comment]
Hi, This has been discussed in other issues as well. You will have to create a custom build with all your plugins included and use that build with this react-ckeditor component. 

Please refer this issue - #7 

PS. I am closing this issue since its duplicate. Feel free to re-open it if it does not solve your problem.

**Comment by ghost** [comment]
Thanks. You are awesome.

**Comment by codeslayer1** [comment]
Welcome. Happy to help :)
