### ISSUE TITLE
Upload image from computer ??

### ISSUE THREAD

**Issue by nguyenkhoi2806** [codeslayer1/react-ckeditor#9]
where i can find Upload tags in image

**Comment by codeslayer1** [comment]
Please add a brief description/example of what you are trying to ask. Your question is not clear.

**Comment by nguyenkhoi2806** [comment]
where is button upload image from computer ???

**Comment by codeslayer1** [comment]
Please read the CKEditor documentation. This library is just a wrapper of CKEditor in React. If you want to upload image, add an image uploader plugin to your CKEditor build and use that custom build in your project (refer documentation in README). 

Closing this issue since its totally unrelated to the library.
